-- Create a table for storing government notices
create table if not exists public.notices (
  id bigint generated by default as identity primary key,
  title text not null,
  agency text,
  start_date date,
  end_date date,
  region text,
  category text,
  url text unique not null, -- URL is used as a unique identifier to prevent duplicates
  source text,
  description text,
  fetched_at timestamptz default now(),
  created_at timestamptz default now()
);

-- Allow public read access (for the website to display notices)
alter table public.notices enable row level security;

create policy "Allow public read access"
  on public.notices for select
  using ( true );

-- Allow authenticated (service role or anon with valid key if configured) insert/update
-- For this demo, assuming service role is used for backend insertions or anon if policies allow.
-- Since we do upsert from the API route (server-side), we use the Service Role key usually, 
-- but here we might be using the Anon key if RLS allows.
-- Let's enable insert for anon for now to make it easy, or just use Service Role in the backend.
create policy "Allow anon insert/update for demo"
  on public.notices for insert
  with check ( true );
  
create policy "Allow anon update for demo"
  on public.notices for update
  using ( true );
